// React/hello_react_demo/react_staging/03_src_TodoList案例/src/components/List/index.jsx
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import Item from '../Item'
import './index.css'

export default class List extends Component {
    static propTypes = {
        updateTodo: PropTypes.func.isRequired,
        todos: PropTypes.array.isRequired
    }
    render() {
        const {todos} = this.props
        return (
            <div className="todo-main">
                {
                    todos.map((todo)=>{
                        return <Item updateTodo={this.props.updateTodo} deleteTodo={this.props.deleteTodo} key={todo.id} todo={todo}/>
                    })
                }
            </div>
        )
    }
}

// Vue/Vue3/my-project/src/components/List.vue
<template>
  <ul class="todo-main">
    <Item v-for="(todo,index) in todos" :key="todo.id" :todo="todo" :deleteTodo="deleteTodo" :index="index" :updateTodo="updateTodo"/>
  </ul>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Item from './Item.vue'
export default defineComponent({
  name: "List",
  components: {
    Item
  },
  props: ['todos','deleteTodo','updateTodo']
});
</script>

<style scoped>
/*main*/
.todo-main {
  margin-left: 0px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding: 0px;
}

.todo-empty {
  height: 40px;
  line-height: 40px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding-left: 5px;
  margin-top: 10px;
}
</style>
